# AcmeDemoBundle routes (to be removed)
_acme_demo:
    resource: "@AcmeDemoBundle/Resources/config/routing.yml"

whoami:
    resource: Acme\DemoBundle\Controller\WhoamiController
    type:     rest

user:
    resource: Acme\DemoBundle\Controller\UserController
    type:     rest

activity:
    resource: Acme\DemoBundle\Controller\ActivityController
    type:     rest

location_update:
    resource: Acme\DemoBundle\Controller\LocationUpdateController
    type:     rest

dashboard:
    resource: Acme\DemoBundle\Controller\DashboardController
    type:     rest
